resources:
- name: node-exporter-release
  type: github-release
  source:
    owner: prometheus
    repository: node_exporter

- name: centos-packer
  type: git
  source:
    uri: https://github.com/sneakybeaky/centos-packer-pipeline.git
    branch: master    

- name: packer-manifest
  type: s3
  source:
    bucket: ami-pipeline-artifacts.ninedemons.io
    versioned_file: base-ami/packer-manifest.json
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}    

jobs:
- name: build-ami
  plan:
  - get: centos-packer
    trigger: true
  - get: node-exporter-release
    trigger: true
    params:
      globs: 
        - "*linux-amd64.tar.gz"
  - task: build
    file: centos-packer/ci/build-ami.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}  
  - put: packer-manifest
    params: {file: built-artifact/packer-manifest.json}

- name: test-ami
  plan:
  - get: centos-packer
    passed: [build-ami]    
  - get: packer-manifest
    trigger: true
    passed: [build-ami]    
  - task: test
    file: centos-packer/ci/test-ami.yml  
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}