resources:
- name: node-exporter-release
  type: github-release
  source:
    owner: prometheus
    repository: node_exporter

- name: centos-packer
  type: git
  source:
    uri: https://github.com/sneakybeaky/centos-packer-pipeline.git
    branch: master    

jobs:
- name: build-ami
  plan:
  - get: centos-packer
  - get: node-exporter-release
    params:
      globs: 
        - "*linux-amd64.tar.gz"
        
  - task: build
    file: centos-packer/ci/build-ami.yml