---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

inputs:
- name: packer-centos

#outputs:
#- name: packer-centos

run:
  path: ./packer-centos/ci/scripts/ami-build

