#!/bin/bash
# vim: set ft=sh

set -x

export AWS_SSH_KEY_ID=TestKitchen

aws ec2 create-key-pair --region eu-west-2 --key-name ${AWS_SSH_KEY_ID} --query 'KeyMaterial' --output text > ${HOME}/test_kitchen.pem || exit 1
chmod 400 ${HOME}/test_kitchen.pem
export SSH_KEY_PATH=${HOME}/test_kitchen.pem

cd centos-packer/tests
kitchen test
ret_code=$?

aws ec2 delete-key-pair --region eu-west-2 --key-name ${AWS_SSH_KEY_ID}

exit $ret_code