#!/bin/bash
# vim: set ft=sh

set -e -x

pushd centos-packer/packer
    packer build -var-file=../centos-ami/packer.json centos.json
popd

cp  centos-packer/packer/packer-manifest.json built-artifact/packer-manifest.json